# German company register courts
REGISTER_COURTS = [
	"",  # empty string to be able to select nothing
	"Aachen",
	"Altenburg",
	"Amberg",
	"Ansbach",
	"Apolda",
	"Arnsberg",
	"Arnstadt",
	"Arnstadt Zweigstelle Ilmenau",
	"Aschaffenburg",
	"Augsburg",
	"Aurich",
	"Bad Hersfeld",
	"Bad Homburg v.d.H.",
	"Bad Kreuznach",
	"Bad Oeynhausen",
	"Bad Salzungen",
	"Bamberg",
	"Bayreuth",
	"Berlin (Charlottenburg)",
	"Bielefeld",
	"Bochum",
	"Bonn",
	"Braunschweig",
	"Bremen",
	"Chemnitz",
	"Coburg",
	"Coesfeld",
	"Cottbus",
	"Darmstadt",
	"Deggendorf",
	"Dortmund",
	"Dresden",
	"Duisburg",
	"Düren",
	"Düsseldorf",
	"Eisenach",
	"Erfurt",
	"Eschwege",
	"Essen",
	"Flensburg",
	"Frankfurt am Main",
	"Frankfurt/Oder",
	"Freiburg",
	"Friedberg",
	"Fritzlar",
	"Fulda",
	"Fürth",
	"Gelsenkirchen",
	"Gera",
	"Gießen",
	"Gotha",
	"Göttingen",
	"Greiz",
	"Gütersloh",
	"Hagen",
	"Hamburg",
	"Hamm",
	"Hanau",
	"Hannover",
	"Heilbad Heiligenstadt",
	"Hildburghausen",
	"Hildesheim",
	"Hof",
	"Homburg",
	"Ingolstadt",
	"Iserlohn",
	"Jena",
	"Kaiserslautern",
	"Kassel",
	"Kempten (Allgäu)",
	"Kiel",
	"Kleve",
	"Koblenz",
	"Köln",
	"Königstein",
	"Korbach",
	"Krefeld",
	"Landau",
	"Landshut",
	"Langenfeld",
	"Lebach",
	"Leipzig",
	"Lemgo",
	"Limburg",
	"Lübeck",
	"Ludwigshafen a.Rhein (Ludwigshafen)",
	"Lüneburg",
	"Mainz",
	"Mannheim",
	"Marburg",
	"Meiningen",
	"Memmingen",
	"Merzig",
	"Mönchengladbach",
	"Montabaur",
	"Mühlhausen",
	"München",
	"Münster",
	"Neubrandenburg",
	"Neunkirchen",
	"Neuruppin",
	"Neuss",
	"Nordhausen",
	"Nürnberg",
	"Offenbach am Main",
	"Oldenburg (Oldenburg)",
	"Osnabrück",
	"Ottweiler",
	"Paderborn",
	"Passau",
	"Pinneberg",
	"Pößneck",
	"Pößneck Zweigstelle Bad Lobenstein",
	"Potsdam",
	"Recklinghausen",
	"Regensburg",
	"Rostock",
	"Rudolstadt",
	"Saarbrücken",
	"Saarlouis",
	"Schweinfurt",
	"Schwerin",
	"Siegburg",
	"Siegen",
	"Sömmerda",
	"Sondershausen",
	"Sonneberg",
	"Stadthagen",
	"Stadtroda",
	"Steinfurt",
	"Stendal",
	"St. Ingbert (St Ingbert)",
	"Stralsund",
	"Straubing",
	"Stuttgart",
	"St. Wendel (St Wendel)",
	"Suhl",
	"Tostedt",
	"Traunstein",
	"Ulm",
	"Völklingen",
	"Walsrode",
	"Weiden i. d. OPf.",
	"Weimar",
	"Wetzlar",
	"Wiesbaden",
	"Wittlich",
	"Wuppertal",
	"Würzburg",
	"Zweibrücken",
]
